//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_beadandó_F9bobl
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTable
    {
        public int Id { get; set; }
        public string Branch { get; set; }
        public string City { get; set; }
        public string Customer_type { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Product_line { get; set; }
        public Nullable<double> Unit_price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Total { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Payment { get; set; }
        public Nullable<double> Cogs { get; set; }
        public Nullable<double> Gross_margin_percentage { get; set; }
        public Nullable<double> Gross_income { get; set; }
        public Nullable<double> Rating { get; set; }
    
        public virtual ProductLines ProductLines { get; set; }
    }
}
